[tool.poetry]
name = "bunq-ynab-connect"
version = "0.1.0"
description = "Automatically classify Bunq transactions and add to Ynab"
authors = ["Aucke Bos <aucke.bos97@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "bunq_ynab_connect"}]

[tool.poetry.dependencies]
python = "^3.8"
mlflow = "^2.6.0"
bunq-sdk = "^1.14.18"
ynab = "^0.0.3"
prefect = "^2.11.4"
scikit-learn = "^1.3.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
autoflake = "^2.2.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
