# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

target-version = "py310"

[lint]
select = ["ALL"]
ignore = [
    "COM812",
    "D107", # Docstring init method
    "D100", # Docstring for public module
    "D102", # Require docstring
    "ANN204", # Return type on init
    "S301", # Pickle
    "FIX002", # TODO
    "TD", # TODO
    "D417", # Missing param docstring. Shows weird behaviour
    "D104", # Missing docstring in public package
    "S101", # Disallow asserts
    "D203", # No blank line before class
    "D213", # Multi line summary first line
    "I001", # Unsorted imports. Somehow fails during build, while sorts are OK. Temp disable to succeed build.
    "ERA001", # Commented code
    "D103", # Docstring in public method
    "N803", # Parameter should be lowercase
] 

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[format]
# Like Black, use double quotes for strings.
quote-style = "double"



# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

docstring-code-format = true

docstring-code-line-length = "dynamic"

# Like Black, indent with spaces, rather than tabs.
