version: '3.7'
services:
  mongodb:
    image: mongo:4.2.0
    container_name: bunqynab_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - bunq_ynab_connect_data:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express:latest
    container_name: bunqynab_mongo_ui
    ports:
      - 12001:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    restart: unless-stopped

  prefect-server:
    image: prefecthq/prefect:2.11.3-python3.8
    container_name: bunqynab_prefect_server
    restart: unless-stopped
    volumes:
      - bunq_ynab_connect_prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=${PREFECT_SERVER_API_HOST}
      # If you want to access Prefect Server from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL to match the external hostname/IP used to load the  UI in your web browser.      
      - PREFECT_API_URL=${PREFECT_API_URL_FOR_SERVER}
    ports:
      - 12002:4200

  prefect-agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile  
    container_name: bunqynab_prefect_agent
    restart: unless-stopped
    env_file:
      - ../.docker-env
    volumes:
      - ../bunq_ynab_connect:/home/bunqynab/bunq_ynab_connect
      - ../config:/home/bunqynab/config
    depends_on:
      - prefect-server

  watchtower:
    image: containrrr/watchtower
    container_name: bunqynab_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 prefect-agent
    restart: unless-stopped

volumes:
  bunq_ynab_connect_data:
  bunq_ynab_connect_prefect:

networks:
  default:
    name: bunq-ynab-network