services:
  # devcontainer
  dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: dev
    env_file:
      - ../.env
    volumes:
      - ../bunq_ynab_connect:/home/bunqynab/bunq_ynab_connect:cached
      - ../config:/home/bunqynab/config:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - prefect-server

  prefect-agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    pull_policy: builds # never pull, always build
    env_file:
      - ../.env
    volumes: !override
      - ../bunq_ynab_connect:/home/bunqynab/bunq_ynab_connect:cached
      - ../config:/home/bunqynab/config:cached
      - /var/run/docker.sock:/var/run/docker.sock

  mlserver:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    pull_policy: builds # never pull, always build
    env_file:
      - ../.env
    volumes: !override
      - ../bunq_ynab_connect:/home/bunqynab/bunq_ynab_connect:cached
      - ../config:/home/bunqynab/config:cached
      - /var/run/docker.sock:/var/run/docker.sock

  callback:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    pull_policy: builds # never pull, always build
    env_file:
      - ../.env
    volumes: !override
      - ../bunq_ynab_connect:/home/bunqynab/bunq_ynab_connect:cached
      - ../config:/home/bunqynab/config:cached
      - /var/run/docker.sock:/var/run/docker.sock
