version: "3.3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.21.1
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.auckebos.nl`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=homeresolver"
      - "traefik.http.routers.callback.tls=true"
    networks:
      - traefik


volumes:
  portainer_data:
    external: true
    name: portainer_data
  

networks:
  traefik:
    name: traefik
    external: true