services:
  # devcontainer
  dev:
    build:
      context: ../.devcontainer
      dockerfile: Dockerfile
      args:
        USERNAME: dev
        PYTHON_VERSION: 3.11
    container_name: dev
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prefect-server

  prefect-agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    pull_policy: build # never pull, always build
    env_file: !override
      - ../.env
    volumes: !override
      - ../bunq_ynab_connect:/home/bunqynab/bunq_ynab_connect:cached
      - ../config:/home/bunqynab/config:cached
      - /var/run/docker.sock:/var/run/docker.sock

  # mlserver:
  #   image: !reset null  
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile
  #   env_file: !override
  #     - ../.env
  #   volumes: !override
  #     - ../:/home/bunqynab:cached
  #     # - ../config:/home/bunqynab/config:cached
  #     - /var/run/docker.sock:/var/run/docker.sock

  # callback:
  #   image: !reset null  
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile
  #   env_file: !override
  #     - ../.env
  #   volumes: !override
  #     - ../:/home/bunqynab:cached
  #     # - ../config:/home/bunqynab/config:cached
  #     - /var/run/docker.sock:/var/run/docker.sock
