services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    container_name: bunqynab_dev
    env_file:
      - ../.docker-env
    volumes:
      - ..:/workspaces/bunq-ynab-connect:cached
      - /var/run/docker.sock:/var/run/docker.sock
    # Keep container running; VS Code will exec your shell
    command: sleep infinity
    # Share the same default network declared in docker/development.yml
    networks:
      - default

networks:
  default:
    name: bunq
